apiVersion: v1
kind: BuildConfig
metadata:
  name: apollo-portal-uat
  namespace: infly
  selfLink: /oapi/v1/namespaces/infly/buildconfigs/apollo-portal-uat
  labels:
    app: apollo-portal-uat
    application: apollo-portal-uat
    xpaas: 1.3.2
spec:
  triggers:
    - type: Generic
      generic:
        secret: gitcae
    - type: ConfigChange
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'git@github.com:vanpersl/apollo.git'
      ref: master
    sourceSecret:
      name: gitcae
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'apollo-portal-s2i:0.0.1'
      env:
        - name: MAVEN_SET_URL
          value: 'http://xxx.xxx.xxx/open/nexus/raw/master/settings.xml'
        - name: MAVEN_ARGS
          value: >-
            -Dspring_datasource_url=jdbc:oracle:thin:@10.221.221.221:1523:ORA130T
            -Dspring_datasource_username=ApolloPortalDB
            -Dspring_datasource_password=1111111
            -Ddev_meta=http://dev.apollo.shift.x
            -Duat_meta=http://uat.apollo.shift.x
  output:
    to:
      kind: ImageStreamTag
      name: 'apollo-portal-uat-s2i:latest'
  resources: {}
  postCommit: {}
  nodeSelector: null
status:
