apiVersion: v1
kind: BuildConfig
metadata:
  name: apollo-meta-uat
  namespace: infly
  selfLink: /oapi/v1/namespaces/infly/buildconfigs/apollo-meta-uat
  labels:
    app: apollo-meta-uat
    application: apollo-meta-uat
    template: apollo-meta-uat-s2i
    xpaas: 1.3.2
spec:
  triggers:
    - type: Generic
      generic:
        secret: gitcae
    - type: ConfigChange
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'git@github.com:vanpersl/apollo.git'
      ref: master
    sourceSecret:
      name: gitcae
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: apollo-meta-s2i
      env:
        - name: MAVEN_ARGS_APPEND
          value: >-
            -Dspring_datasource_url=jdbc:oracle:thin:@10.221.221.221:1523:ORA130T
            -Dspring_datasource_username=ApolloConfigDB
            -Dspring_datasource_password=111111
            -Dspring_jpa_hibernate_default_schema=ApolloConfigDB
        - name: MAVEN_SET_URL
          value: 'http://xxx.xxx.com/open/nexus/raw/master/settings.xml'
  output:
    to:
      kind: ImageStreamTag
      name: 'apollo-meta-uat-s2i:latest'
  resources: {}
  postCommit: {}
  nodeSelector: null
status:
